CMAKE_COMMON_FLAGS += -DUSERVER_FEATURE_CRYPTOPP_BLAKE=0 -DUSERVER_DOWNLOAD_PACKAGE_CRYPTOPP=1 -DUSERVER_FEATURE_GRPC_CHANNELZ=0


.PHONY: start
start:
	@cd build_release \
		&& ./portfolio --config ../configs/static_config.yaml

.PHONY: run
run: install start