worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

# portfolio_db_1 is the service name + _ + filename of the public.sql
dbconnection: 'postgresql://testsuite@localhost:15433/portfolio_db_1'
